title: "Daniel Vaughan"
email: "website@danielvaughan.com"
url: "https://danielvaughan.com"
twitter_username: "@DanielVaughan"
github_username:  "danielvaughan"
# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
# A list of the pages to display in the navigation bar
header_pages:
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - "*.sh"
  - CLAUDE.md
  - context/
  - redundant/
  - index.old.html
  - .playwright-mcp/
